### ISSUE TITLE
Missing dependencies when installing from pip "tracking-head"

### ISSUE THREAD

**Issue by TiTi87** [google/grr-doc#50]
Just run a install on fresh Xenial 16.04, following ["installing-grr-server-for-dev-ie-tracking-head"](https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head), and after running `install_script_ubuntu.sh` : 
it seems that some dependencies as missing in the first apt-get install.

I needed to also install : 

- `libffi-dev protobuf-compiler` 
- `protobuf-c-compiler` 
- `protobuf-compiler`

 in order to get this procedure working.

Also note, if running as root, bower will refuse to run, so if you want to disable this protection :
`echo '{ "allow_root": true }' > /root/.bowerrc`
but this is not an error....

Thanks
https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-from-pip

**Comment by destijl** [comment]
thanks, I added those to the docs. The bower case is interesting, if you want to run using the init scripts you need to disable that protection, but that means you can't ever run as a regular user again:

https://github.com/bower/bower/issues/498

because that protection is there for a reason. We can add a warning, but that's not a great solution. Adding @mbushkov to see if he has any ideas.

**Comment by destijl** [comment]
After discussing with misha, bower runs here:

```
pip install --editable .
```

which, if you followed the instructions, shouldn't be run as root. So I think we're good here.
