### ISSUE TITLE
GRR agent not installing on Windows

### ISSUE THREAD

**Issue by dyizah** [google/grr-doc#68]
When I execute the GRR agent install file it doesn't completely install on my Windows Clients. I can see the process and service that starts up but few seconds later it will die. Anyone experienced this before?

**Comment by grrrrrrrrr** [comment]
Have you tried the steps suggested in the troubleshooting guide?
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc

**Comment by mored276** [comment]
The grr agent is not installed on 32 bit windows xp. They know how to fix that problem. The same agent does not fail to install on win7.

**Comment by destijl** [comment]
We don't support XP. It's very hard to make everything work on such an old OS, and there is no benefit for us since we don't have it:
https://github.com/google/grr-doc/blob/master/faq.adoc#what-operating-system-versions-does-the-client-support

If you're having trouble with supported OSes follow the troubleshooting steps and re-open with error backtraces if you need help.

**Comment by khurram0334** [comment]
i have grr server isntalled in ubuntu v machine. and installed client in window 10 via exe file. but grr server is not loading client what can be the problem and how to resolve it pls

**Comment by khurram0334** [comment]
nany.status service stoped in window client. how to resolve it pls

**Comment by mbushkov** [comment]
@khurram0334 - please see https://grr-doc.readthedocs.io/en/latest/deploying-grr-clients/troubleshooting.html#troubleshooting-i-don-t-see-my-clients
Unfortunately it's impossible to say what went wrong with the client without a log or a stacktrace.
